# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/corpress',
                'doc_host': 'https://geoffford.nz',
                'git_url': 'https://github.com/polsci/corpress',
                'lib_path': 'corpress'},
  'syms': {'corpress.core': {'corpress.core.foo': ('core.html#foo', 'corpress/core.py')}}}
